@ECHO OFF
SET DIRNAME=%~dp0
IF "%DIRNAME%" == "" SET DIRNAME=.
SET APP_BASE_NAME=%~n0
SET GRADLE_WRAPPER_DIR=%DIRNAME%\gradle\wrapper

IF EXIST "%DIRNAME%\.gradle" SET GRADLE_USER_HOME=%DIRNAME%\.gradle

SET JAVA_EXE=%JAVA_HOME%\bin\java.exe
IF NOT EXIST "%JAVA_EXE%" SET JAVA_EXE=java

"%JAVA_EXE%" %JAVA_OPTS% -jar "%GRADLE_WRAPPER_DIR%\gradle-wrapper.jar" %*
